version: "3.8"

services:
  app:
    image: py-feat:1.2
    network_mode: host
    container_name: feat
    volumes:
      - "./feat:/usr/local/lib/python3.10/site-packages/feat"   
      - "./main:/app/main"
      - "/vdb/structure/test_data:/data"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - DATA_MOUNT=/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # 正确写法：command 使用列表
    command: [
      "uvicorn",
      "main.app:app",
      "--host", "0.0.0.0",
      "--port", "9099",
      "--workers", "4"
    ]

    ports:
      - "9099:9099"

